version: "3"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: todoList
      MYSQL_USER: root
      MYSQL_PASSWORD: 1
    volumes:
      - "./todo.sql:/docker-entrypoint-initdb.d/todo.sql"
    expose:
      - "3306"
  dropwizard-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


